---
# Consul web UI: http://192.168.77.21:8500/ui
# DNS: dig @172.17.0.1 -p 53 manager2.node.consul
#
- hosts: managers
  become: yes
  become_user: root
  roles:
    - role: consul
      consul_servers_group: managers


- hosts: workers
  become: yes
  become_user: root
  roles:
    - role: consul
      consul_servers_group: managers
      consul_mode: agent

# Registrator doesn't work with Docker 1.12 services at the moment
# though will work with containers running via docker run
- hosts: managers[0]
  become: yes
  become_user: root
  tasks:
    - name: Start registrator globally and connect to consul cluster
      shell: >
        docker service create \
          --name registrator \
          --mount type=bind,target=/tmp/docker.sock,src=/var/run/docker.sock \
          --network appnet \
          --mode global \
          gliderlabs/registrator:latest \
          consul://{{ hostvars[inventory_hostname]['ansible_docker0']['ipv4']['address'] }}:8500
      tags:
        - registrator


