logstash_config: syslog-collectd.conf

directories: [
  { path: "/data/logstash/conf", mode: "0755" },
  { path: "/data/logstash/logs", mode: "0777" },
]

files: [
  { src: "beats.conf", dest: "/data/logstash/conf/beats.conf" },
  { src: "syslog-collectd.conf", dest: "/data/logstash/conf/syslog-collectd.conf" },
  { src: "apache.log", dest: "/tmp/apache.log" },
  { src: "apache2.log", dest: "/tmp/apache2.log" }
]
