NUM_OF_MANAGERS: 3
NUM_OF_WORKERS: 2
MEMORY: 1024
VIDEO_MEMORY: 25
NUM_CPUS: 2

# Update the machines (sudo apt-get), takes more time
UPDATE_MACHINES: false

VBGUEST_UPDATE: false
VBGUEST_NO_REMOTE: true

# Initialize the managers
SWARM_INIT_MANAGERS: true
# Initialize the workers, only applicable if also managers are initialized
SWARM_INIT_WORKERS: true
# Only applicable if there is more than 1 worker
SWARM_DEPLOY_STACK: true
