# ---------------------------------------------------------------------------
# GENERAL SETTINGS
# ---------------------------------------------------------------------------

# Box to use on VirtualBox.
VM_BOX: "ubuntu/trusty64"

# Update the machines (sudo apt-get). Note: takes quite a lot of time
UPDATE_MACHINES: false

# Update VBGuest
VBGUEST_UPDATE: false

# Prevent downloading VBGuest binaries from remote
VBGUEST_NO_REMOTE: true

## Bridged Network:
NETWORK_BRIDGED: true
## Network settings, name of the network device
NETWORK_BRIDGED_DEFAULT: "Realtek PCIe GBE Family Controller #2"


# ---------------------------------------------------------------------------
# MULTI-MACHINE CONFIGURATION
# ---------------------------------------------------------------------------

NUM_OF_MANAGERS: 3
NUM_OF_WORKERS: 2
MEMORY_MANAGER: 2048
MEMORY_WORKER: 2048
VIDEO_MEMORY: 25
NUM_CPUS_MANAGER: 2
NUM_CPUS_WORKER: 2

# ---------------------------------------------------------------------------
# DOCKER SWARM INITIALIZATION
# ---------------------------------------------------------------------------

# Initialize the managers
SWARM_INIT_MANAGERS: true

# Initialize the workers, only applicable if also managers are initialized
SWARM_INIT_WORKERS: true

# ---------------------------------------------------------------------------
# DOCKER SWARM - STACK DEPLOYMENT
# ---------------------------------------------------------------------------

# Only applicable if there is more than 1 worker
SWARM_DEPLOY_STACK: true


# ---------------------------------------------------------------------------
# ADVANCED OPTIONS
# ---------------------------------------------------------------------------


# Definition of forwarded_ports (see more: https://www.vagrantup.com/docs/networking/forwarded_ports.html)
FORWARDED_PORTS:
#  - id: ssh-external
#    host_ip: 127.0.0.1
#    guest: 22
#    host: 2223
#    protocol: tcp
#    disabled: false
#    auto_correct: true
#    vm: manager-1

# Mount shared/sync-folders (see: https://www.vagrantup.com/docs/synced-folders/basic_usage.html)
SYNCED_FOLDERS:
  #- src: ""
  #  mount: ""
